#!/usr/bin/env python3
"""
Generates webview-ui/src/data/searchEntries.generated.ts by reading the
REAL sample files under demo-project/ so that every mock search result's
code preview and line numbers are 100% accurate to the files the
extension will actually open. Re-run this script if demo-project files
change.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT = ROOT
OUT = os.path.join(ROOT, "webview-ui", "src", "data", "searchEntries.generated.ts")

ENTRIES = [
    dict(
        id="authenticate-user",
        name="authenticate_user",
        className=None,
        file="backend/auth/service.py",
        start=30, end=47,
        tags=["jwt", "authentication", "auth", "login", "authenticate", "user",
              "password", "token", "credential", "verify"],
        baseScore=94.21,
    ),
    dict(
        id="verify-token",
        name="verify_token",
        className=None,
        file="backend/auth/jwt.py",
        start=31, end=44,
        tags=["jwt", "token", "verify", "validate", "authentication", "decode",
              "expired", "signature"],
        baseScore=89.73,
    ),
    dict(
        id="create-access-token",
        name="create_access_token",
        className=None,
        file="backend/auth/jwt.py",
        start=19, end=27,
        tags=["jwt", "token", "generate", "create", "access", "sign",
              "authentication", "issue"],
        baseScore=87.05,
    ),
    dict(
        id="login-route",
        name="login",
        className=None,
        file="backend/routes/auth.py",
        start=18, end=37,
        tags=["login", "route", "endpoint", "authentication", "jwt", "api",
              "http", "post"],
        baseScore=84.12,
    ),
    dict(
        id="get-db-session",
        name="get_db_session",
        className=None,
        file="backend/db/connection.py",
        start=26, end=44,
        tags=["database", "db", "connection", "session", "postgresql",
              "sqlalchemy", "engine", "create"],
        baseScore=91.5,
    ),
    dict(
        id="check-connection",
        name="check_connection",
        className=None,
        file="backend/db/connection.py",
        start=47, end=54,
        tags=["database", "connection", "health", "check", "ping"],
        baseScore=76.8,
    ),
    dict(
        id="save-upload",
        name="save_upload",
        className=None,
        file="backend/uploads/handler.py",
        start=30, end=48,
        tags=["upload", "file", "save", "storage", "validation", "write"],
        baseScore=92.6,
    ),
    dict(
        id="validate-upload",
        name="validate_upload",
        className=None,
        file="backend/uploads/handler.py",
        start=19, end=27,
        tags=["upload", "validation", "file", "extension", "size", "check"],
        baseScore=88.4,
    ),
    dict(
        id="get-by-username",
        name="get_by_username",
        className="UserRepository",
        file="backend/db/repository.py",
        start=17, end=24,
        tags=["user", "repository", "database", "query", "lookup",
              "username", "find"],
        baseScore=82.9,
    ),
]

def main():
    out_entries = []
    for e in ENTRIES:
        path = os.path.join(PROJECT, e["file"])
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()
        snippet = lines[e["start"] - 1:e["end"]]
        code_lines = [line.rstrip("\n") for line in snippet]
        out_entries.append({
            "id": e["id"],
            "name": e["name"],
            "className": e["className"],
            "file": e["file"],
            "startLine": e["start"],
            "endLine": e["end"],
            "tags": e["tags"],
            "baseScore": e["baseScore"],
            "code": code_lines,
        })

    ts = []
    ts.append("// AUTO-GENERATED by scripts/gen_mockdata.py — do not hand-edit.")
    ts.append("// Regenerate with: python3 scripts/gen_mockdata.py")
    ts.append("// Every `code` snippet below is copied verbatim from the real files")
    ts.append("// in demo-project/, so search results in the demo point at real code.")
    ts.append("")
    ts.append("export interface GeneratedSearchEntry {")
    ts.append("  id: string;")
    ts.append("  name: string;")
    ts.append("  className: string | null;")
    ts.append("  file: string;")
    ts.append("  startLine: number;")
    ts.append("  endLine: number;")
    ts.append("  tags: string[];")
    ts.append("  baseScore: number;")
    ts.append("  code: string[];")
    ts.append("}")
    ts.append("")
    ts.append("export const generatedSearchEntries: GeneratedSearchEntry[] = " +
               json.dumps(out_entries, indent=2) + ";")
    ts.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(ts))
    print(f"Wrote {OUT} with {len(out_entries)} entries")

if __name__ == "__main__":
    main()
